console.log("Hello JavaScript");
const arr=[2,3,4,5,6,7];

const double=arr.map(num=>num*2)
console.log(double);

console.log("Hello jnana");
var userName=" Jnana";
console.log(userName + ", Welcome to code practice ");


//changes by jnana
const numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

const evenNumbers = numbers.filter(num => num % 2 === 0);

console.log(evenNumbers); // Output: [2, 4, 6, 8, 10]
console.log("This is from 2nd loudu lallit");
console.log("This is 3rd Loudu lallit");
